### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by MaManama** [AcridStingray3/Meeting-Auto-Recorder#1]
When I start up the .json file it says
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 9 column 2 of the JSON data

**Comment by BasedJellyfish11** [comment]
I'd ask you what you mean with "start up the .json file".

If you mean hitting the Start button on the script, and not double clicking the json or something similar, you probably wrote something weird on line 9
